### ISSUE TITLE
Cheatsheet request: Rust

### ISSUE THREAD

**Issue by dragoscirjan** [Randy8080/reference#119]
Hi! Would like to see a Rust cheatsheet here :) 

I'm pretty sure it will be the next language that I touch (after Golang) and it would actually be nice to have a cheatsheet also :)

**Comment by xelemental** [comment]
Hi, I have created a pull request for the same, hope the maintainer accepts it.

**Comment by Randy8080** [comment]
@xelemental Thanks for the contribution! 

The Rust cheatsheet has been formatted and published on https://quickref.me/rust
