### ISSUE TITLE
[C#] Typos and improvements in range

### ISSUE THREAD

**Issue by QHopp** [Randy8080/reference#123]
Hello and thank you for your site !

I noticed some errors in the C# page such as 

## User input
Console.ReadLine() returns a `string` and not an `int` (that conversion isn't implicit)
[Example](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBfsQJwAUARAKIwICmyABDKmMByAYBKANwVYCbr04BeTgGEA9jADOigDZsAdACU2EDABlYbOqKq1GATUWpObVhzYZODTtilhRQA==)

## Arrays
- Two ; missing (sorry I'm doing the compiler job here :P )
- `boolean[]` doesn't exit in C# but `bool` yes 

## Loops
The name of the property is `Length` and not `length`

## Variables
- The floating-point numeric types are a little bit special and need literal suffixes : 
`M` for decimal
`F` for floats

- You can't name variables with keywords, if you want to do that you can prefix your variables with `@` like in `bool @bool = true`

[Example](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBbAgATUByqYNAvDQJwDcFANgPYwA5jX5DGzNuynSuFAGb8ItBXyXjWHAHRSAYt3IY+qYDwCmNQ8bPrJ7bVP0ZTAYyiQeFl24g8bHOzIAsvrOABYQyCKmCAimkWwA5AAiCfrAfHwe+PjpmRoIaKb6+MQADDQAzlCxGgBEAI6oUM4A1simcppgprX6AG4RNDBMGtL9gxUFddK9FAOR6RpyPhVFQA==)
Try to remove the things I mentioned here to see the problem

## Primitive data types
You could add the decimal range since you added the float and double one
It's [28-29 digits](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types)

## Hello.cs
The main method is named `Main` in C#, that's mandatory
[Example](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUEQAQASApgDYMD2VA3hVVQPTdWSx+dBAAtmyDJyr5iANmkAWftBgAKGQAYA2gF0qEZAHMAzgEopHcly68qAeVQIADo5C1GLOFQDu4hhgBCKS4ZAE5VACJ6JmYvX2R/AIjTAG4pAF8KdKA)

Furthermore, we now have top level statements that lessen the need of the whole OOP construction
```cs
using System; // This also can be omitted thanks to implicit usings (since .NET 6) but let's forget that
Console.WriteLine("Hello World"); 
```
⬆️ This is valid since .NET 6
[Example](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAAwCwAUEQIwAEF+VAnABQBEAEgKYA23A9jQDqfZNwysAlAG4aQA)

**Comment by Randy8080** [comment]
Hi, Thank you for your hard work!
