### ISSUE TITLE
Cheatsheet request: tmux

### ISSUE THREAD

**Issue by MCotocel** [Randy8080/reference#17]
## A clear description of what you want
- A cheatsheet for tmux

## Refer URL
- https://man7.org/linux/man-pages/man1/tmux.1.html

**Comment by matu3ba** [comment]
[What is missing in this one?](https://tmuxcheatsheet.com/)

**Comment by MCotocel** [comment]
That's a difference site, isn't it? It could be used as a reference, but it would be nice to have it in this site.

**Comment by Randy8080** [comment]
https://quickref.me/tmux

done!
