### ISSUE TITLE
Cheatsheet request: netcat / nc

### ISSUE THREAD

**Issue by Fechin** [Randy8080/reference#4]
## A clear description of what you want
- Some common examples
- Parameter explanation
- And more

## Refer URL
- https://en.wikipedia.org/wiki/Netcat
- https://www.tecmint.com/netcat-nc-command-examples/
- https://kapeli.com/cheat_sheets/Netcat.docset/Contents/Resources/Documents/index

**Comment by Randy8080** [comment]
https://quickref.me/nc
Done!
