### ISSUE TITLE
Cheatsheet request: Rust

### ISSUE THREAD

**Issue by void00r** [Randy8080/reference#45]
I love how you present and visualize all commands and options in your cheatsheets.
here some sources i found that might be useful for you to add into a Rust programming language cheatsheet
- https://cheats.rs/
- https://phaiax.github.io/rust-cheatsheet/
- https://programming-idioms.org/cheatsheet/Go/Rust

**Comment by Randy8080** [comment]
Hello there, 

The Late Rust cheat sheet here: [https://quickref.me/rust](https://quickref.me/rust), It may not be the best yet, let's make it better

Thanks!
